FROM mcr.microsoft.com/dotnet/sdk:7.0

RUN usermod -u 1000 www-data
RUN curl -k -L https://github.com/Samsung/netcoredbg/releases/download/2.2.0-961/netcoredbg-linux-amd64.tar.gz \
    --output netcoredbg.tar.gz && tar -xzf netcoredbg.tar.gz -C "/" && rm netcoredbg.tar.gz
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet tool install --global dotnet-ef

WORKDIR /app

ENTRYPOINT [ "dotnet", "./bin/Debug/net7.0/sharpcada.dll" ]
