#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
ENV_FILE=$SCRIPTPATH/../docker/.env

export $(grep -v '^#' "$ENV_FILE" | xargs)

docker-compose --env-file $ENV_FILE \
    -f $SCRIPTPATH/../docker/docker-compose.yml \
    -f $SCRIPTPATH/../docker/docker-compose.${APP_ENV}.yml $@
