version: '3.1'

services:

  server:
    container_name: sharpcada-server
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ../www/:/usr/share/nginx/html/
    working_dir: /usr/share/nginx/html
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      APP_PORT: ${APP_PORT}
    restart: ${DOCKER_RESTART}
    networks:
      - internal
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile.${APP_ENV}
    container_name: sharpcada-app
    restart: ${DOCKER_RESTART}
    env_file:
      - ../.env
    environment:
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}
    networks:
      - internal
  db:
    image: postgres:15
    container_name: sharpcada-db
    restart: ${DOCKER_RESTART}
    volumes:
      - ../db_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - internal

networks:
    internal:
