version: '3.1'

services:

  server:
    ports:
      - ${SERVER_PORT}:80
  app:
    volumes:
      - ../srcback/:/app
    command: dotnet restore
    ports:
      - 5711:4711
  db:
    ports:
      - ${DB_PORT}:5432
